const shopData = {
    shopItems: [
      {
      id: 1,
      discount: 5,
      name: "Baby Doll Lara",
      img: "/assets/babydolllara/conjunto (4).jpg",
      price: 12,
      desc: "O Baby Doll Lara oferece conforto e delicadeza, ideal para noites tranquilas e relaxantes.",
    },
    {
      id: 2,
      discount: 5,
      name: "Baby Doll Plus Estampado",
      img: "/assets/babydollplus rosa/conjunto (2).jpg",
      price: 18,
      desc: "Com estampas modernas, o Baby Doll Plus Estampado traz estilo e alegria para o seu descanso.",
    },
    {
      id: 3,
      discount: 5,
      name: "Baby Doll Plus Lisa",
      img: "/assets/estampadorosa/conjunto (3).jpg",
      price: 18,
      desc: "O Baby Doll Plus Lisa é perfeito para quem busca simplicidade e conforto em todos os momentos.",
    },
    {
      id: 4,
      discount: 5,
      name: "Camisola Lisa (P)",
      img: "/assets/camisolarosa/conjunto (2).jpg",
      price: 14,
      desc: "A Camisola Lisa tamanho P é básica, confortável e ideal para noites de sono tranquilas.",
    },
    {
      id: 5,
      discount: 5,
      name: "Camisola Lisa (M)",
      img: "/assets/camisolarosa/conjunto (2).jpg",
      price: 14,
      desc: "A Camisola Lisa tamanho M proporciona leveza e suavidade para o seu descanso.",
    },
    {
      id: 6,
      discount: 5,
      name: "Camisola Lisa (G)",
      img: "/assets/camisolarosa/conjunto (2).jpg",
      price: 14,
      desc: "A Camisola Lisa tamanho G é perfeita para quem busca conforto e praticidade.",
    },
    {
      id: 7,
      discount: 5,
      name: "Camisola Lisa (GG)",
      img: "/assets/camisolarosa/conjunto (2).jpg",
      price: 14,
      desc: "A Camisola Lisa tamanho GG oferece ajuste ideal e muito conforto para suas noites.",
    },
    {
      id: 8,
      discount: 5,
      name: "Baby Doll Estampado (M)",
      img: "/assets/estampadovermelho/conunto (3).jpg",
      price: 13,
      desc: "O Baby Doll Estampado M traz alegria e leveza com suas estampas exclusivas.",
    },
    {
      id: 9,
      discount: 5,
      name: "Baby Doll Estampado (G)",
      img: "/assets/estampadovermelho/conunto (3).jpg",
      price: 13,
      desc: "O Baby Doll Estampado G é ideal para quem gosta de dormir com estilo e conforto.",
    },
    {
      id: 10,
      discount: 5,
      name: "Baby Doll Estampado (GG)",
      img: "/assets/estampadovermelho/conunto (3).jpg",
      price: 13,
      desc: "O Baby Doll Estampado GG une praticidade e charme para suas noites.",
    },
    {
      id: 11,
      discount: 5,
      name: "Camisola Valmir (M)",
      img: "/assets/camisolarosa/conjunto (3).jpg",
      price: 14,
      desc: "A Camisola Valmir M é elegante e confortável, perfeita para noites especiais.",
    },
    {
      id: 12,
      discount: 5,
      name: "Camisola Valmir (G)",
      img: "/assets/camisolarosa/conjunto (3).jpg",
      price: 14,
      desc: "A Camisola Valmir G oferece sofisticação e maciez para o seu descanso.",
    },
    {
      id: 13,
      discount: 5,
      name: "Camisola Valmir (GG)",
      img: "/assets/camisolarosa/conjunto (3).jpg",
      price: 14,
      desc: "A Camisola Valmir GG é ideal para quem busca elegância e conforto em tamanho maior.",
    },
    ],
  }
  export default shopData;