const shopData = {
    shopItems: [
      {
        id: 1,
        discount: 10,
        img: "/assets/babydolllara/conjunto (3).jpg",
        name: "Baby Doll Lara",
        price: 35,
        desc: "Confortável e elegante, o Baby Doll Lara é perfeito para noites relaxantes. Feito com tecido macio e acabamento delicado.",
      },
      {
        id: 2,
        discount: 15,
        img: "/assets/babydollplus rosa/conjunto (3).jpg",
        name: "Baby Doll Plus",
        price: 40,
        desc: "O Baby Doll Plus combina estilo e conforto, ideal para quem busca um toque especial no dia a dia.",
      },
      {
        id: 3,
        discount: 5,
        img: "/assets/estampadorosa/conjunto (4).jpg",
        name: "Camisola Estampada",
        price: 35,
        desc: "Com estampas modernas, a Camisola Estampada traz charme e leveza para suas noites.",
      },
      {
        id: 4,
        discount: 20,
        img: "/assets/camisolarosa/conjunto (3).jpg",
        name: "Camisola Lisa",
        price: 40,
        desc: "A Camisola Lisa é uma peça básica e sofisticada, ideal para quem aprecia simplicidade com elegância.",
      },
      {
        id: 5,
        discount: 10,
        img: "/assets/estampadovermelho/conunto (2).jpg",
        name: "Baby Doll Floral",
        price: 35,
        desc: "Com estampas florais delicadas, o Baby Doll Floral é perfeito para noites românticas.",
      },
      {
        id: 6,
        discount: 15,
        img: "/assets/camisolarosa/conjunto (4).jpg",
        name: "Camisola Longa",
        price: 40,
        desc: "A Camisola Longa oferece conforto e sofisticação, ideal para noites mais frias.",
      },
      {
        id: 7,
        discount: 5,
        img: "/assets/babydollpreto/conjunto (2).jpg",
        name: "Baby Doll Renda",
        price: 35,
        desc: "Com detalhes em renda, o Baby Doll Renda é uma peça delicada e cheia de charme.",
      },
      {
        id: 8,
        discount: 10,
        img: "/assets/camisolavermelha/conjunto (4).jpg",
        name: "Camisola Curta",
        price: 40,
        desc: "A Camisola Curta é leve e confortável, perfeita para noites quentes.",
      },
      {
        id: 9,
        discount: 20,
        img: "/assets/babydollpreto/conjunto (4).jpg",
        name: "Baby Doll Elegance",
        price: 35,
        desc: "O Baby Doll Elegance combina conforto e sofisticação, ideal para momentos especiais.",
      },
      {
        id: 10,
        discount: 15,
        img: "/assets/camisolavermelha/conjunto (3).jpg",
        name: "Camisola Estampada Floral",
        price: 40,
        desc: "Com estampas florais vibrantes, a Camisola Estampada Floral é perfeita para quem ama cores.",
      },
      {
        id: 11,
        discount: 5,
        img: "/assets/babydollplus rosa/conjunto (4).jpg",
        name: "Baby Doll Confort",
        price: 35,
        desc: "O Baby Doll Confort é ideal para quem busca conforto sem abrir mão do estilo.",
      },
      {
        id: 12,
        discount: 10,
        img: "/assets/camisolavermelha/conjunto (3).jpg",
        name: "Camisola de Seda",
        price: 40,
        desc: "A Camisola de Seda é uma peça luxuosa, perfeita para noites especiais.",
      },
      {
        id: 13,
        discount: 20,
        img: "/assets/babudollazul/conjunto (2).jpg",
        name: "Baby Doll Estampado",
        price: 35,
        desc: "Com estampas modernas, o Baby Doll Estampado é uma peça cheia de personalidade.",
      },
      {
        id: 14,
        discount: 15,
        img: "/assets/camisolarosa/conjunto (2).jpg",
        name: "Camisola Básica",
        price: 40,
        desc: "A Camisola Básica é uma peça versátil e confortável, ideal para o dia a dia.",
      },
      {
        id: 15,
        discount: 5,
        img: "/assets/babydollpreto/conjunto (2).jpg",
        name: "Baby Doll Noite",
        price: 35,
        desc: "O Baby Doll Noite é perfeito para noites tranquilas, com tecido leve e macio.",
      },
      {
        id: 16,
        discount: 10,
        img: "/assets/camisolarosa/conjunto (2).jpg",
        name: "Camisola Elegante",
        price: 40,
        desc: "A Camisola Elegante é uma peça sofisticada, ideal para quem busca estilo e conforto.",
      },
      {
        id: 17,
        discount: 20,
        img: "/assets/babydollplus rosa/conjunto (2).jpg",
        name: "Baby Doll Delicado",
        price: 35,
        desc: "Com detalhes delicados, o Baby Doll Delicado é perfeito para momentos especiais.",
      },
      {
        id: 18,
        discount: 15,
        img: "/assets/camisolavermelha/conjunto (2).jpg",
        name: "Camisola Romântica",
        price: 40,
        desc: "A Camisola Romântica é ideal para noites cheias de charme e conforto.",
      },
      {
        id: 19,
        discount: 5,
        img: "/assets/babydolllara/conjunto (2).jpg",
        name: "Baby Doll Casual",
        price: 35,
        desc: "O Baby Doll Casual é uma peça prática e confortável, perfeita para o dia a dia.",
      },
      {
        id: 20,
        discount: 10,
        img: "/assets/camisolapreto/conjunto (1).jpg",
        name: "Camisola Luxo",
        price: 40,
        desc: "A Camisola Luxo é uma peça sofisticada, ideal para quem busca exclusividade.",
      },
    ],
  }
  export default shopData;