const allProductsData = {
  allProductsData: [
    {
      id: 1,
      name: "Baby Doll Lara",
      img: "/assets/babydolllara/conjunto (4).jpg",
      price: 12,
      desc: "O Baby Doll Lara oferece conforto e delicadeza, ideal para noites tranquilas e relaxantes.",
    },
    {
      id: 2,
      name: "Baby Doll Plus Estampado",
      img: "/assets/babydollplus rosa/conjunto (2).jpg",
      price: 18,
      desc: "Com estampas modernas, o Baby Doll Plus Estampado traz estilo e alegria para o seu descanso.",
    },
    {
      id: 3,
      name: "Baby Doll Plus Lisa",
      img: "/assets/estampadorosa/conjunto (3).jpg",
      price: 18,
      desc: "O Baby Doll Plus Lisa é perfeito para quem busca simplicidade e conforto em todos os momentos.",
    },
    {
      id: 4,
      name: "Camisola Lisa (P)",
      img: "/assets/camisolarosa/conjunto (2).jpg",
      price: 14,
      desc: "A Camisola Lisa tamanho P é básica, confortável e ideal para noites de sono tranquilas.",
    },
    {
      id: 5,
      name: "Camisola Lisa (M)",
      img: "/assets/camisolarosa/conjunto (2).jpg",
      price: 14,
      desc: "A Camisola Lisa tamanho M proporciona leveza e suavidade para o seu descanso.",
    },
    {
      id: 6,
      name: "Camisola Lisa (G)",
      img: "/assets/camisolarosa/conjunto (2).jpg",
      price: 14,
      desc: "A Camisola Lisa tamanho G é perfeita para quem busca conforto e praticidade.",
    },
    {
      id: 7,
      name: "Camisola Lisa (GG)",
      img: "/assets/camisolarosa/conjunto (2).jpg",
      price: 14,
      desc: "A Camisola Lisa tamanho GG oferece ajuste ideal e muito conforto para suas noites.",
    },
    {
      id: 8,
      name: "Baby Doll Estampado (M)",
      img: "/assets/estampadovermelho/conunto (3).jpg",
      price: 13,
      desc: "O Baby Doll Estampado M traz alegria e leveza com suas estampas exclusivas.",
    },
    {
      id: 9,
      name: "Baby Doll Estampado (G)",
      img: "/assets/estampadovermelho/conunto (3).jpg",
      price: 13,
      desc: "O Baby Doll Estampado G é ideal para quem gosta de dormir com estilo e conforto.",
    },
    {
      id: 10,
      name: "Baby Doll Estampado (GG)",
      img: "/assets/estampadovermelho/conunto (3).jpg",
      price: 13,
      desc: "O Baby Doll Estampado GG une praticidade e charme para suas noites.",
    },
    {
      id: 11,
      name: "Camisola Valmir (M)",
      img: "/assets/camisolarosa/conjunto (3).jpg",
      price: 14,
      desc: "A Camisola Valmir M é elegante e confortável, perfeita para noites especiais.",
    },
    {
      id: 12,
      name: "Camisola Valmir (G)",
      img: "/assets/camisolarosa/conjunto (3).jpg",
      price: 14,
      desc: "A Camisola Valmir G oferece sofisticação e maciez para o seu descanso.",
    },
    {
      id: 13,
      name: "Camisola Valmir (GG)",
      img: "/assets/camisolarosa/conjunto (3).jpg",
      price: 14,
      desc: "A Camisola Valmir GG é ideal para quem busca elegância e conforto em tamanho maior.",
    },
    {
      id: 14,
      name: "Baby Luxo (P)",
      img: "/assets/babydollpreto/conjunto (3).jpg",
      price: 12,
      desc: "O Baby Luxo P traz um toque sofisticado e delicado para suas noites.",
    },
    {
      id: 15,
      name: "Baby Luxo (M)",
      img: "/assets/babydollpreto/conjunto (3).jpg",
      price: 12,
      desc: "O Baby Luxo M combina elegância e conforto para o seu sono.",
    },
    {
      id: 16,
      name: "Baby Luxo (G)",
      img: "/assets/babydollpreto/conjunto (3).jpg",
      price: 12,
      desc: "O Baby Luxo G é perfeito para quem busca um visual refinado e confortável.",
    },
    {
      id: 17,
      name: "Baby Luxo (GG)",
      img: "/assets/babydollpreto/conjunto (3).jpg",
      price: 12,
      desc: "O Baby Luxo GG oferece sofisticação e ajuste perfeito para noites especiais.",
    },
    {
      id: 18,
      name: "Camisola Suede (M)",
      img: "/assets/camisolavermelha/conjunto (3).jpg",
      price: 14,
      desc: "A Camisola Suede M é macia e elegante, ideal para noites de puro conforto.",
    },
    {
      id: 19,
      name: "Camisola Suede (G)",
      img: "/assets/camisolavermelha/conjunto (3).jpg",
      price: 14,
      desc: "A Camisola Suede G proporciona aconchego e estilo para o seu descanso.",
    },
    {
      id: 20,
      name: "Camisola Suede (GG)",
      img: "/assets/camisolavermelha/conjunto (3).jpg",
      price: 14,
      desc: "A Camisola Suede GG é perfeita para quem busca maciez e elegância em tamanho maior.",
    },
    {
      id: 21,
      name: "Baby Doll Virginia Full (M)",
      img: "/assets/babydollpreto/conjunto (3).jpg",
      price: 14,
      desc: "O Baby Doll Virginia Full M une conforto e charme para suas noites.",
    },
    {
      id: 22,
      name: "Baby Doll Virginia Full (G)",
      img: "/assets/babydollpreto/conjunto (3).jpg",
      price: 14,
      desc: "O Baby Doll Virginia Full G é ideal para quem gosta de dormir com estilo.",
    },
    {
      id: 23,
      name: "Baby Doll Virginia Full (GG)",
      img: "/assets/babydollpreto/conjunto (3).jpg",
      price: 14,
      desc: "O Baby Doll Virginia Full GG oferece conforto e beleza para o seu sono.",
    },
    {
      id: 24,
      name: "Baby Doll Virginia Infantil",
      img: "/assets/camisolavermelha/conjunto (3).jpg",
      price: 15,
      desc: "O Baby Doll Virginia Infantil é delicado e confortável, perfeito para as pequenas.",
    },
    {
      id: 25,
      name: "Baby Doll Liso (P)",
      img: "/assets/babydollpreto/conjunto (3).jpg",
      price: 14,
      desc: "O Baby Doll Liso P é básico, confortável e ideal para o dia a dia.",
    },
    {
      id: 26,
      name: "Baby Doll Liso (M)",
      img: "/assets/babydollpreto/conjunto (3).jpg",
      price: 14,
      desc: "O Baby Doll Liso M oferece praticidade e conforto para suas noites.",
    },
    {
      id: 27,
      name: "Baby Doll Liso (G)",
      img: "/assets/babydollpreto/conjunto (3).jpg",
      price: 14,
      desc: "O Baby Doll Liso G é perfeito para quem busca simplicidade e bem-estar.",
    },
    {
      id: 28,
      name: "Baby Doll Liso (GG)",
      img: "/assets/babydollpreto/conjunto (3).jpg",
      price: 14,
      desc: "O Baby Doll Liso GG proporciona conforto e ajuste ideal para o seu descanso.",
    },
    {
      id: 29,
      name: "Lingerie Cropped Tule (p)",
      img: "/assets/camisolavermelha/conjunto (3).jpg",
      price: 24,
      desc: "A Lingerie Cropped Tule P é sensual e delicada, perfeita para ocasiões especiais.",
    },
    {
      id: 30,
      name: "Lingerie Cropped Tule (M)",
      img: "/assets/camisolavermelha/conjunto (3).jpg",
      price: 24,
      desc: "A Lingerie Cropped Tule M traz charme e elegância para o seu dia a dia.",
    },
    {
      id: 31,
      name: "Lingerie Cropped Tule (G)",
      img: "/assets/camisolavermelha/conjunto (3).jpg",
      price: 24,
      desc: "A Lingerie Cropped Tule G é ideal para quem busca sensualidade e conforto.",
    },
    {
      id: 32,
      name: "Conjunto Andreza (P)",
      img: "/assets/babydollpreto/conjunto (3).jpg",
      price: 20,
      desc: "O Conjunto Andreza P é moderno e confortável, perfeito para o dia a dia.",
    },
    {
      id: 33,
      name: "Conjunto Andreza (M)",
      img: "/assets/babydollpreto/conjunto (3).jpg",
      price: 20,
      desc: "O Conjunto Andreza M oferece praticidade e estilo para todas as ocasiões.",
    },
    {
      id: 34,
      name: "Conjunto Andreza (G)",
      img: "/assets/babydollpreto/conjunto (3).jpg",
      price: 20,
      desc: "O Conjunto Andreza G é ideal para quem busca conforto e beleza.",
    },
    {
      id: 35,
      name: "Samba Canção Infantil (M)",
      img: "/assets/babydollpreto/conjunto (3).jpg",
      price: 14,
      desc: "O Samba Canção Infantil M é leve e confortável, perfeito para os pequenos.",
    },
    {
      id: 36,
      name: "Samba Canção Infantil (G)",
      img: "/assets/babydollpreto/conjunto (3).jpg",
      price: 14,
      desc: "O Samba Canção Infantil G proporciona liberdade e conforto para as crianças.",
    },
    {
      id: 37,
      name: "Samba Canção Infantil (GG)",
      img: "/assets/babydollpreto/conjunto (3).jpg",
      price: 14,
      desc: "O Samba Canção Infantil GG é ideal para noites tranquilas e confortáveis.",
    },
    {
      id: 38,
      name: "Samba Canção Adulto (P)",
      img: "/assets/camisolavermelha/conjunto (3).jpg",
      price: 15,
      desc: "O Samba Canção Adulto P é prático e confortável, ideal para o dia a dia.",
    },
    {
      id: 39,
      name: "Samba Canção Adulto (M)",
      img: "/assets/camisolavermelha/conjunto (3).jpg",
      price: 15,
      desc: "O Samba Canção Adulto M oferece liberdade de movimentos e conforto.",
    },
    {
      id: 40,
      name: "Samba Canção Adulto (G)",
      img: "/assets/camisolavermelha/conjunto (3).jpg",
      price: 15,
      desc: "O Samba Canção Adulto G é perfeito para quem busca praticidade e bem-estar.",
    },
    {
      id: 41,
      name: "Samba Canção Adulto (GG)",
      img: "/assets/camisolavermelha/conjunto (3).jpg",
      price: 15,
      desc: "O Samba Canção Adulto GG proporciona conforto e ajuste ideal.",
    },
    {
      id: 42,
      name: "Samba Canção Adulto (XXG)",
      img: "/assets/camisolavermelha/conjunto (3).jpg",
      price: 15,
      desc: "O Samba Canção Adulto XXG é amplo e confortável, ideal para todos os momentos.",
    },
    {
      id: 43,
      name: "Camisola no Tule (M)",
      img: "/assets/babydollpreto/conjunto (3).jpg",
      price: 18,
      desc: "A Camisola no Tule M é delicada e sensual, perfeita para noites especiais.",
    },
    {
      id: 44,
      name: "Camisola no Tule (G)",
      img: "/assets/babydollpreto/conjunto (3).jpg",
      price: 18,
      desc: "A Camisola no Tule G oferece leveza e elegância para o seu descanso.",
    },
    {
      id: 45,
      name: "Camisola no Tule (GG)",
      img: "/assets/babydollpreto/conjunto (3).jpg",
      price: 18,
      desc: "A Camisola no Tule GG é ideal para quem busca sensualidade e conforto.",
    },
    {
      id: 46,
      name: "Conjunto com Bojo Lore (P)",
      img: "/assets/camisolavermelha/conjunto (3).jpg",
      price: 22,
      desc: "O Conjunto com Bojo Lore P oferece sustentação e beleza para o seu dia a dia.",
    },
    {
      id: 47,
      name: "Conjunto com Bojo Lore (M)",
      img: "/assets/camisolavermelha/conjunto (3).jpg",
      price: 22,
      desc: "O Conjunto com Bojo Lore M é confortável e elegante, ideal para todas as ocasiões.",
    },
    {
      id: 48,
      name: "Conjunto com Bojo Lore (G)",
      img: "/assets/camisolavermelha/conjunto (3).jpg",
      price: 22,
      desc: "O Conjunto com Bojo Lore G proporciona ajuste perfeito e muito charme.",
    },
    {
      id: 49,
      name: "Conjunto com Bojo Lore (GG)",
      img: "/assets/camisolavermelha/conjunto (3).jpg",
      price: 22,
      desc: "O Conjunto com Bojo Lore GG é ideal para quem busca conforto e sustentação.",
    },
    {
      id: 50,
      name: "Baby Doll Lia",
      img: "/assets/babydollpreto/conjunto (3).jpg",
      price: 15,
      desc: "O Baby Doll Lia é delicado e confortável, perfeito para noites de descanso.",
    },
    {
      id: 51,
      name: "Lingerie Conjunto Encanto (P)",
      img: "/assets/camisolavermelha/conjunto (3).jpg",
      price: 20,
      desc: "O Conjunto Encanto P é sofisticado e confortável, ideal para o dia a dia.",
    },
    {
      id: 52,
      name: "Lingerie Conjunto Encanto (M)",
      img: "/assets/camisolavermelha/conjunto (3).jpg",
      price: 20,
      desc: "O Conjunto Encanto M oferece charme e conforto para todas as ocasiões.",
    },
    {
      id: 53,
      name: "Lingerie Conjunto Encanto (G)",
      img: "/assets/camisolavermelha/conjunto (3).jpg",
      price: 20,
      desc: "O Conjunto Encanto G é perfeito para quem busca elegância e bem-estar.",
    },
    {
      id: 54,
      name: "Lingerie Conjunto Encanto (GG)",
      img: "/assets/camisolavermelha/conjunto (3).jpg",
      price: 20,
      desc: "O Conjunto Encanto GG proporciona ajuste ideal e muito conforto.",
    },
    {
      id: 55,
      name: "Conjunto Tulipa (P)",
      img: "/assets/babydollpreto/conjunto (3).jpg",
      price: 19,
      desc: "O Conjunto Tulipa P é moderno e delicado, perfeito para o dia a dia.",
    },
    {
      id: 56,
      name: "Conjunto Tulipa (M)",
      img: "/assets/babydollpreto/conjunto (3).jpg",
      price: 19,
      desc: "O Conjunto Tulipa M oferece conforto e estilo para todas as ocasiões.",
    },
    {
      id: 57,
      name: "Conjunto Tulipa (G)",
      img: "/assets/babydollpreto/conjunto (3).jpg",
      price: 19,
      desc: "O Conjunto Tulipa G é ideal para quem busca praticidade e beleza.",
    },
  ],
};

export default allProductsData;