const flashDealsData = {
  productItems: [
    {
      id: 1,
      discount: 15,
      img: "/assets/camisolavermelha/conjunto (4).jpg",
      name: "Camisola Romântica",
      price: 40,
    },
    {
      id: 2,
      discount: 5,
      img: "/assets/babydolllara/conjunto (4).jpg",
      name: "Baby Doll Casual",
      price: 35,
    },
    {
      id: 3,
      discount: 10,
      img: "/assets/camisolapreto/conjunto (4).jpg",
      name: "Camisola Luxo",
      price: 40,
    },
    {
      id: 4,
      discount: 5,
      img: "/assets/babydollpreto/conjunto (4).jpg",
      name: "Baby Doll Noite",
      price: 35,
    },
    {
      id: 5,
      discount: 10,
      img: "/assets/camisolarosa/conjunto (4).jpg",
      name: "Camisola Elegante",
      price: 40,
    },
    {
      id: 6,
      discount: 10,
      img: "/assets/camisolapreto/conjunto (2).jpg",
      name: "Camisola Luxo",
      price: 40,
    },
    {
      id: 7,
      discount: 15,
      img: "/assets/camisolavermelha/conjunto (3).jpg",
      name: "Camisola Romântica",
      price: 40,
    },
    {
      id: 8,
      discount: 5,
      img: "/assets/babydolllara/conjunto (2).jpg",
      name: "Baby Doll Casual",
      price: 35,
    },
    {
      id: 9,
      discount: 10,
      img: "/assets/camisolapreto/conjunto (3).jpg",
      name: "Camisola Luxo",
      price: 40,
    },
    {
      id: 10,
      discount: 5,
      img: "/assets/babydollpreto/conjunto (3).jpg",
      name: "Baby Doll Noite",
      price: 35,
    },
    {
      id: 11,
      discount: 10,
      img: "/assets/camisolarosa/conjunto (5).jpg",
      name: "Camisola Elegante",
      price: 40,
    },
    {
      id: 12,
      discount: 10,
      img: "/assets/camisolapreto/conjunto (4).jpg",
      name: "Camisola Luxo",
      price: 40,
    },
  ],
};

export default flashDealsData;
